// Code generated by MockGen. DO NOT EDIT.
// Source: url-checker/init.go

// Package urlchecker_mock is a generated GoMock package.
package urlchecker_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLChecker is a mock of URLChecker interface.
type MockURLChecker struct {
	ctrl     *gomock.Controller
	recorder *MockURLCheckerMockRecorder
}

// MockURLCheckerMockRecorder is the mock recorder for MockURLChecker.
type MockURLCheckerMockRecorder struct {
	mock *MockURLChecker
}

// NewMockURLChecker creates a new mock instance.
func NewMockURLChecker(ctrl *gomock.Controller) *MockURLChecker {
	mock := &MockURLChecker{ctrl: ctrl}
	mock.recorder = &MockURLCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLChecker) EXPECT() *MockURLCheckerMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockURLChecker) Validate(rawURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", rawURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockURLCheckerMockRecorder) Validate(rawURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockURLChecker)(nil).Validate), rawURL)
}
